- The app should be modular; I want to develop it in stages so that it’s easy to ensure the systems are coherent and so that the code and functionality can be scaled.
- I want to start with basic text notes that support Markdown, along with some UI elements that aren’t Markdown-based. For example, it should be easy to create tables and add images and videos.
- At the same time, it’s important not to overload the app with graphical features. Above all, it needs to be fast and robust.
- I want to have a Graph view like in Obsidian—one that shows all notes and their links to each other.
- The app will follow a “local first” approach; initially, it will even be “local only.” However in the future, this should scale to allow for storage on my own hosting
- Images, videos, and other attachments used in notes will also be stored locally in the corresponding folders/libraries e.g. a folder that only contains pictures from the entire vault
- I want a UI similar to Notion, and a note format that supports nesting within folders and links between notes
- I want the option to create an emoji or vector icon for each note. Ideally, I’d like to use the emoji library from Twitter/Discord
- It would be nice to have a backup feature that saves the entire vault as an archive when the corresponding button is clicked in the settings. And this archive would be stored on the computer separately from the vault
- It’s important to me that, when I switch to self-hosting later, I can use the same vault on both my phone and my PC. And I’d like to use Conflict-free Replicated Data Type to avoid overriding conflicts
- I’d also like a separate section for quick note, which would be a page that support only text stored like a regular note but have its own dedicated space in the UI
- A calendar where you can mark events and time periods, and link notes to specific dates and events
- It would be nice to have a multilingual spell-checker with the ability to add your own words and terms to the dictionary.
- A locally running AI agent that lets you interact with your notes. For example, you could ask it to find information related to biology across all your notes. Or ask it to create a note about this or that, or to create an event in the app’s calendar with a specific time. Maybe even with voice control. 
- A home page with links to important notes, recent notes, and perhaps widgets that the user can choose to add there.
