// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Suggested default vault location for the "don't make me think" path:
	 *  `{Documents}/Tundra` (CLAUDE.md §5.1).
	 */
	defaultVaultPath: () => typedError<string, CoreError>(__TAURI_INVOKE("default_vault_path")),
	/**  The last vault opened, if any — lets the app skip onboarding on relaunch. */
	lastVault: () => typedError<string | null, CoreError>(__TAURI_INVOKE("last_vault")),
	/**  Open (or create) the vault at `path`, remember it, and return its info. */
	openVault: (path: string) => typedError<VaultInfo, CoreError>(__TAURI_INVOKE("open_vault", { path })),
	/**  Info about the currently open vault, or `None` if onboarding is needed. */
	currentVault: () => typedError<{
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
} | null, CoreError>(__TAURI_INVOKE("current_vault")),
	listNotes: () => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("list_notes")),
	createNote: (title: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_note", { title })),
	/**
	 *  Create a note directly inside `folder` (relative to the notes root, `""`
	 *  for the root) — the "new note in the selected folder" nav action.
	 */
	createNoteIn: (title: string, folder: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_note_in", { title, folder })),
	/**
	 *  Read the single quick-note scratchpad (Phase 2 step 5), or a fresh empty one
	 *  if nothing's been captured yet. It's not one of the vault's notes — it lives
	 *  in its own file and never appears in the tree/search/graph.
	 */
	readQuickNote: () => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("read_quick_note")),
	/**
	 *  Persist the quick-note scratchpad. Deliberately does NOT touch the search or
	 *  link indexes — the quick note is outside the notes tree.
	 */
	saveQuickNote: (note: Note_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("save_quick_note", { note })),
	/**  Every template's shallow summary (id/title/icon), title-sorted. */
	listTemplates: () => typedError<TemplateSummary_Serialize[], CoreError>(__TAURI_INVOKE("list_templates")),
	/**  Create a new, empty template and return it. */
	createTemplate: (title: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_template", { title })),
	/**  Read a template's full document by id. */
	readTemplate: (id: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("read_template", { id })),
	/**
	 *  Persist an edited template (validated + atomic, like a note). Deliberately
	 *  does NOT touch the search or link indexes — templates are outside the notes tree.
	 */
	saveTemplate: (note: Note_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("save_template", { note })),
	/**  Delete a template by id. */
	deleteTemplate: (id: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_template", { id })),
	readNote: (id: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("read_note", { id })),
	saveNote: (note: Note_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("save_note", { note })),
	deleteNote: (id: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_note", { id })),
	/**
	 *  Vault cleanup (settings): delete every note whose body is empty, regardless of
	 *  title (see `Note::is_empty`). Mirrors `delete_note`'s index upkeep for each
	 *  removed note and returns the ids that were deleted (the frontend shows the
	 *  count and refreshes the tree). Notes carrying an image/table/other embed are
	 *  kept.
	 */
	cleanupEmptyNotes: () => typedError<string[], CoreError>(__TAURI_INVOKE("cleanup_empty_notes")),
	moveNote: (id: string, newFolder: string) => typedError<null, CoreError>(__TAURI_INVOKE("move_note", { id, newFolder })),
	/**  The folder/note tree for the open vault. */
	listTree: () => typedError<TreeNode_Serialize[], CoreError>(__TAURI_INVOKE("list_tree")),
	createFolder: (path: string) => typedError<null, CoreError>(__TAURI_INVOKE("create_folder", { path })),
	renameFolder: (path: string, newName: string) => typedError<null, CoreError>(__TAURI_INVOKE("rename_folder", { path, newName })),
	moveFolder: (path: string, newParent: string) => typedError<null, CoreError>(__TAURI_INVOKE("move_folder", { path, newParent })),
	deleteFolder: (path: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_folder", { path })),
	/**
	 *  Copy `src_path` (chosen via the native file dialog in `services`) into
	 *  `attachments/icons/`, returning its vault-relative path for `Icon::Custom`.
	 */
	importIcon: (srcPath: string) => typedError<string, CoreError>(__TAURI_INVOKE("import_icon", { srcPath })),
	/**
	 *  Copy `src_path` (chosen via the native file dialog in `services`) into the
	 *  vault's `attachments/images/` library for use as a note banner, returning its
	 *  vault-relative path for `Banner::Image`.
	 */
	importBanner: (srcPath: string) => typedError<string, CoreError>(__TAURI_INVOKE("import_banner", { srcPath })),
	/**
	 *  Import an attachment by content (Phase 2 step 1): the frontend reads a
	 *  browser `File`'s bytes and forwards them here; the core hashes them (blake3),
	 *  stores them content-addressed under `attachments/<kind>/`, and returns the
	 *  vault-relative path the editor stores in the embedding block. No attachment
	 *  bytes are ever written from the frontend.
	 */
	importAttachment: (kind: AttachmentKind, fileName: string, bytes: number[]) => typedError<string, CoreError>(__TAURI_INVOKE("import_attachment", { kind, fileName, bytes })),
	/**  Ranked full-text search hits (id, title, snippet) for `query`. */
	searchQuery: (query: string, limit: number) => typedError<SearchHit[], CoreError>(__TAURI_INVOKE("search_query", { query, limit })),
	/**
	 *  Tag-filtered search hits (id, title, and the note's tag set as snippet) for
	 *  `tag_query` — the global search's `#tag` mode. Matches only the `tags` field.
	 */
	searchByTag: (tagQuery: string, limit: number) => typedError<SearchHit[], CoreError>(__TAURI_INVOKE("search_by_tag", { tagQuery, limit })),
	/**
	 *  Rebuild the search index from scratch (a user-triggered recovery action —
	 *  the index is derived/rebuildable, never a source of truth).
	 */
	rebuildIndex: () => typedError<null, CoreError>(__TAURI_INVOKE("rebuild_index")),
	/**
	 *  Notes that link *to* `id` (incoming links), as current summaries — the
	 *  editor's backlinks panel (Phase 2 step 2).
	 */
	backlinks: (id: string) => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("backlinks", { id })),
	/**
	 *  The whole directed link graph (nodes = notes, edges = resolved links) for
	 *  the graph view (Phase 2 step 2/4). Broken links are excluded.
	 */
	graphData: () => typedError<GraphData_Serialize, CoreError>(__TAURI_INVOKE("graph_data")),
	/**
	 *  Resolve note ids to their CURRENT summaries (title/icon) — for live link
	 *  labels; ids that no longer resolve are omitted (the caller uses the stored
	 *  label for those).
	 */
	resolveTitles: (ids: string[]) => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("resolve_titles", { ids })),
	/**
	 *  Rebuild the link graph from the notes on disk (recovery action — the graph
	 *  cache is derived/rebuildable).
	 */
	rebuildGraph: () => typedError<null, CoreError>(__TAURI_INVOKE("rebuild_graph")),
	/**
	 *  Read a vault-scoped config file under `.vault/config/<name>` (Phase 2 step 4:
	 *  graph view settings; step 6: home dashboard layout). Returns the raw JSON
	 *  string, or `None` if it hasn't been written yet — the caller parses it. This
	 *  keeps vault UI state out of `localStorage` and in the vault where it can sync
	 *  (CLAUDE.md §4/§5.2).
	 */
	readVaultConfig: (name: string) => typedError<string | null, CoreError>(__TAURI_INVOKE("read_vault_config", { name })),
	/**
	 *  Write a vault-scoped config file under `.vault/config/<name>` atomically —
	 *  the FS counterpart of `read_vault_config`.
	 */
	writeVaultConfig: (name: string, contents: string) => typedError<null, CoreError>(__TAURI_INVOKE("write_vault_config", { name, contents })),
	/**
	 *  Read an app-scoped settings blob (a global preference that persists across
	 *  vaults), or `None` if it hasn't been written yet. Returns the raw JSON string;
	 *  the caller parses it (mirrors `read_vault_config`, but app- not vault-scoped).
	 */
	readAppSettings: (name: string) => typedError<string | null, CoreError>(__TAURI_INVOKE("read_app_settings", { name })),
	/**
	 *  Write an app-scoped settings blob atomically (temp file + rename, so a crash
	 *  mid-write never truncates an existing file) — the FS counterpart of
	 *  `read_app_settings`.
	 */
	writeAppSettings: (name: string, contents: string) => typedError<null, CoreError>(__TAURI_INVOKE("write_app_settings", { name, contents })),
	/**  All calendar events in the open vault. */
	listEvents: () => typedError<Event_Serialize[], CoreError>(__TAURI_INVOKE("list_events")),
	/**
	 *  Create an event (a fresh UUID is assigned if `event.id` is empty) and return
	 *  the stored form.
	 */
	createEvent: (event: Event_Deserialize) => typedError<Event_Serialize, CoreError>(__TAURI_INVOKE("create_event", { event })),
	/**  Update an existing event (matched by id). */
	updateEvent: (event: Event_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("update_event", { event })),
	/**  Delete an event by id. */
	deleteEvent: (id: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_event", { id })),
	/**
	 *  Everything on the calendar in the inclusive `[start, end]` day range: both
	 *  standalone events and note→date links (served from the in-memory index).
	 */
	calendarRange: (start: string, end: string) => typedError<CalendarRange_Serialize, CoreError>(__TAURI_INVOKE("calendar_range", { start, end })),
	/**
	 *  Link a note to a date (optionally a specific event), stored on the note's meta
	 *  and mirrored into the index.
	 */
	addNoteDate: (id: string, date: NoteDate_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("add_note_date", { id, date })),
	/**  Remove a note→date link (matched exactly). */
	removeNoteDate: (id: string, date: NoteDate_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("remove_note_date", { id, date })),
	/**
	 *  Set (or clear, with a `null` value) one user-defined property value on a
	 *  note. `value` is a raw JSON string (the serialized property value), or `null`
	 *  to clear the key — the same raw-JSON-string boundary as the config
	 *  passthrough, since specta can't pass an opaque `serde_json::Value` as a
	 *  command arg. The folder table view owns the property-type system; the core
	 *  just stores + mirrors the value for rendering/sorting.
	 */
	setNoteProperty: (id: string, key: string, value: string | null) => typedError<null, CoreError>(__TAURI_INVOKE("set_note_property", { id, key, value })),
	/**  Replace a note's tag set wholesale (trimmed + deduped by the core). */
	setNoteTags: (id: string, tags: string[]) => typedError<null, CoreError>(__TAURI_INVOKE("set_note_tags", { id, tags })),
	/**  Add one tag to a note (no-op if blank or already present). */
	addNoteTag: (id: string, tag: string) => typedError<null, CoreError>(__TAURI_INVOKE("add_note_tag", { id, tag })),
	/**  Remove one tag from a note (exact match). */
	removeNoteTag: (id: string, tag: string) => typedError<null, CoreError>(__TAURI_INVOKE("remove_note_tag", { id, tag })),
	/**
	 *  Rename a tag everywhere it appears in the vault (`from` → `to`). Every note
	 *  carrying the old tag is rewritten and reindexed so the `#tag` search + all
	 *  chips reflect the new name immediately. A no-op if `to` is blank or unchanged.
	 */
	renameTag: (from: string, to: string) => typedError<null, CoreError>(__TAURI_INVOKE("rename_tag", { from, to })),
	/**
	 *  Every distinct tag used in the vault, sorted — the pool for tag suggestions
	 *  and the settings tag manager.
	 */
	listTags: () => typedError<string[], CoreError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Delete a tag from the whole vault (permanent — removes it from every note that
	 *  carries it, unlike `remove_note_tag` which only touches one note). Every
	 *  affected note is reindexed so search + chips drop it immediately.
	 */
	deleteTag: (tag: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_tag", { tag })),
	/**  All Kanban boards (tab order). */
	kanbanBoards: () => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_boards")),
	/**  Create a board (seeded with To do / Doing / Done columns); returns all boards. */
	kanbanCreateBoard: (name: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_create_board", { name })),
	/**  Rename a board. */
	kanbanRenameBoard: (boardId: string, name: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_rename_board", { boardId, name })),
	/**  Delete a board (note tags are left as-is). */
	kanbanDeleteBoard: (boardId: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_delete_board", { boardId })),
	/**  Append a column to a board, optionally with an auto-assign tag. */
	kanbanAddColumn: (boardId: string, name: string, tag: string | null) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_add_column", { boardId, name, tag })),
	/**  Rename a column and/or change its auto-assign tag. */
	kanbanUpdateColumn: (boardId: string, columnId: string, name: string, tag: string | null) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_update_column", { boardId, columnId, name, tag })),
	/**  Delete a column (its cards drop off the board; note tags left as-is). */
	kanbanDeleteColumn: (boardId: string, columnId: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_delete_column", { boardId, columnId })),
	/**  Reorder a board's columns (move `column_id` to `to_index`). */
	kanbanMoveColumn: (boardId: string, columnId: string, toIndex: number) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_move_column", { boardId, columnId, toIndex })),
	/**  Add a note to a column (applies the column's tag). Moves it if already on the board. */
	kanbanAddCard: (boardId: string, columnId: string, noteId: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_add_card", { boardId, columnId, noteId })),
	/**  Move a note to `to_column_id` at `to_index` (swaps the source/destination tags). */
	kanbanMoveCard: (boardId: string, noteId: string, toColumnId: string, toIndex: number) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_move_card", { boardId, noteId, toColumnId, toIndex })),
	/**  Remove a note from a board (strips the tag of the column it was in). */
	kanbanRemoveCard: (boardId: string, noteId: string) => typedError<KanbanBoard_Serialize[], CoreError>(__TAURI_INVOKE("kanban_remove_card", { boardId, noteId })),
	/**
	 *  One-click backup: zip the whole vault (excluding the rebuildable
	 *  `.vault/cache/`) into `dest_dir` — which must be OUTSIDE the vault — verify
	 *  the archive is readable, and return its path. The frontend remembers
	 *  `dest_dir` in app-settings (global, cross-vault).
	 */
	backupVault: (destDir: string) => typedError<string, CoreError>(__TAURI_INVOKE("backup_vault", { destDir })),
	/**
	 *  Misspelled spans in `text` (offsets/lengths in UTF-16 units). Empty when no
	 *  language dictionary is loaded.
	 */
	spellcheckCheck: (text: string) => typedError<Misspelling[], CoreError>(__TAURI_INVOKE("spellcheck_check", { text })),
	/**  Add a word to the per-vault personal dictionary (effective immediately). */
	spellcheckAddWord: (word: string) => typedError<null, CoreError>(__TAURI_INVOKE("spellcheck_add_word", { word })),
	/**  Remove a word from the personal dictionary (Settings; step 6). */
	spellcheckRemoveWord: (word: string) => typedError<null, CoreError>(__TAURI_INVOKE("spellcheck_remove_word", { word })),
	/**  The personal dictionary's words (for the Settings dictionary manager). */
	spellcheckPersonalWords: () => typedError<string[], CoreError>(__TAURI_INVOKE("spellcheck_personal_words")),
	/**  Available (bundled) and enabled spellcheck languages. */
	spellcheckLanguages: () => typedError<SpellLanguages, CoreError>(__TAURI_INVOKE("spellcheck_languages")),
	/**
	 *  Enable exactly `languages` (persisted globally) and apply to the open vault's
	 *  spellchecker immediately.
	 */
	spellcheckSetLanguages: (languages: string[]) => typedError<null, CoreError>(__TAURI_INVOKE("spellcheck_set_languages", { languages })),
};

/** Events */
export const events = {
	noteChangedExternally: makeEvent<NoteChangedExternally>("note-changed-externally"),
	treeChanged: makeEvent<TreeChanged>("tree-changed"),
};

/* Types */
/**
 *  Which attachment library an import lands in (CLAUDE.md §5.2:
 *  `attachments/{images,videos,files}`). Crosses the IPC boundary, so it is
 *  serialized; the frontend maps a file's MIME type onto one of these.
 */
export type AttachmentKind = "image" | "video" | "file";

/**
 *  A note's top-of-page banner (cover): either a built-in gradient preset or a
 *  user-supplied image stored in the vault. Rendered above the title/icon in the
 *  editor. The gradient variant carries only a preset id — the actual CSS lives
 *  in the frontend, so no colours are stored in the vault; the image variant
 *  carries a vault-relative path under `attachments/images/` (portable across
 *  vault moves/sync), resolved to a displayable URL at render time like custom
 *  note icons and editor image embeds.
 */
export type Banner = 
/**  A built-in gradient preset id, e.g. `"blush"`. No vault file. */
{ type: "gradient"; value: string } | 
/**  Vault-relative path of a user image under `attachments/images/`. */
{ type: "image"; value: string };

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block = Block_Serialize | Block_Deserialize;

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Deserialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Deserialize[],
};

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Serialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Serialize[],
};

/**
 *  The combined answer to "what's on the calendar in this range": standalone
 *  events and note→date links, both falling within `[start, end]`.
 */
export type CalendarRange = CalendarRange_Serialize | CalendarRange_Deserialize;

/**
 *  The combined answer to "what's on the calendar in this range": standalone
 *  events and note→date links, both falling within `[start, end]`.
 */
export type CalendarRange_Deserialize = {
	events: Event_Deserialize[],
	note_dates: NoteDateEntry_Deserialize[],
};

/**
 *  The combined answer to "what's on the calendar in this range": standalone
 *  events and note→date links, both falling within `[start, end]`.
 */
export type CalendarRange_Serialize = {
	events: Event_Serialize[],
	note_dates: NoteDateEntry_Serialize[],
};

export type CoreError = 
/**  No vault is currently open, or the path is not a usable vault. */
{ kind: "Vault"; message: string } | 
/**  A requested note could not be found by id. */
{ kind: "NotFound"; message: string } | 
/**  The stored schema version is newer than this build understands. */
{ kind: "SchemaTooNew"; message: {
	found: number,
	supported: number,
} } | 
/**  Underlying filesystem failure. */
{ kind: "Io"; message: string } | 
/**  JSON (de)serialization failure — a corrupt or malformed note file. */
{ kind: "Serde"; message: string } | 
/**  A block in the tree had an empty `id` (violates the CRDT-ready guarantee). */
{ kind: "EmptyBlockId" } | 
/**  The same block `id` appeared more than once in the tree. */
{ kind: "DuplicateBlockId"; message: string };

/**
 *  A first-class calendar event. A single day/instant when `end` is `None`; a
 *  multi-day time period when `end` is set. Times are stored in UTC; `all_day`
 *  tells the UI to render the day span and ignore the clock time. (Range overlap
 *  is computed on the UTC calendar date — a local-timezone refinement can come
 *  later without changing the on-disk shape.)
 */
export type Event = Event_Serialize | Event_Deserialize;

/**
 *  A first-class calendar event. A single day/instant when `end` is `None`; a
 *  multi-day time period when `end` is set. Times are stored in UTC; `all_day`
 *  tells the UI to render the day span and ignore the clock time. (Range overlap
 *  is computed on the UTC calendar date — a local-timezone refinement can come
 *  later without changing the on-disk shape.)
 */
export type Event_Deserialize = {
	id: string,
	title: string,
	start: string,
	end?: string | null,
	all_day?: boolean,
	/**
	 *  Notes linked to this event (optional; the reciprocal of a `NoteDate` whose
	 *  `event_id` points here).
	 */
	note_ids?: string[],
	color?: string | null,
};

/**
 *  A first-class calendar event. A single day/instant when `end` is `None`; a
 *  multi-day time period when `end` is set. Times are stored in UTC; `all_day`
 *  tells the UI to render the day span and ignore the clock time. (Range overlap
 *  is computed on the UTC calendar date — a local-timezone refinement can come
 *  later without changing the on-disk shape.)
 */
export type Event_Serialize = {
	id: string,
	title: string,
	start: string,
	end?: string | null,
	all_day: boolean,
	/**
	 *  Notes linked to this event (optional; the reciprocal of a `NoteDate` whose
	 *  `event_id` points here).
	 */
	note_ids?: string[],
	color?: string | null,
};

export type FolderNode = FolderNode_Serialize | FolderNode_Deserialize;

export type FolderNode_Deserialize = {
	name: string,
	/**
	 *  Forward-slash-separated path relative to the notes root, e.g.
	 *  `"Biology/Plants"` — the same shape every folder-op command takes.
	 */
	path: string,
	children: TreeNode_Deserialize[],
};

export type FolderNode_Serialize = {
	name: string,
	/**
	 *  Forward-slash-separated path relative to the notes root, e.g.
	 *  `"Biology/Plants"` — the same shape every folder-op command takes.
	 */
	path: string,
	children: TreeNode_Serialize[],
};

/**
 *  The whole link graph for the vault: every note as a node, resolved links as
 *  directed edges.
 */
export type GraphData = GraphData_Serialize | GraphData_Deserialize;

/**
 *  The whole link graph for the vault: every note as a node, resolved links as
 *  directed edges.
 */
export type GraphData_Deserialize = {
	nodes: GraphNode_Deserialize[],
	edges: GraphEdge[],
};

/**
 *  The whole link graph for the vault: every note as a node, resolved links as
 *  directed edges.
 */
export type GraphData_Serialize = {
	nodes: GraphNode_Serialize[],
	edges: GraphEdge[],
};

/**
 *  A directed graph edge — note `source` links to note `target`. Only emitted
 *  when both ends resolve to existing notes (broken links are not edges).
 */
export type GraphEdge = {
	source: string,
	target: string,
};

/**  A graph node — one note. */
export type GraphNode = GraphNode_Serialize | GraphNode_Deserialize;

/**  A graph node — one note. */
export type GraphNode_Deserialize = {
	id: string,
	title: string,
	/**
	 *  The note's own icon (set via the same picker as the nav tree) — carried
	 *  through so the graph view can optionally render it in place of the
	 *  default dot instead of re-deriving anything from the title.
	 */
	icon?: Icon | null,
};

/**  A graph node — one note. */
export type GraphNode_Serialize = {
	id: string,
	title: string,
	/**
	 *  The note's own icon (set via the same picker as the nav tree) — carried
	 *  through so the graph view can optionally render it in place of the
	 *  default dot instead of re-deriving anything from the title.
	 */
	icon?: Icon | null,
};

/**  A per-note icon: a Twemoji codepoint or a custom vector/image in the vault. */
export type Icon = 
/**  Twemoji codepoint string, e.g. `"1f331"`. */
{ type: "emoji"; value: string } | 
/**  Path (relative to the vault) of a custom icon under `attachments/icons/`. */
{ type: "custom"; value: string };

/**
 *  A single Kanban board: a name and its ordered columns. Boards are switched
 *  between as tabs in the one Kanban view.
 */
export type KanbanBoard = KanbanBoard_Serialize | KanbanBoard_Deserialize;

/**
 *  A single Kanban board: a name and its ordered columns. Boards are switched
 *  between as tabs in the one Kanban view.
 */
export type KanbanBoard_Deserialize = {
	id: string,
	name: string,
	columns?: KanbanColumn_Deserialize[],
};

/**
 *  A single Kanban board: a name and its ordered columns. Boards are switched
 *  between as tabs in the one Kanban view.
 */
export type KanbanBoard_Serialize = {
	id: string,
	name: string,
	columns: KanbanColumn_Serialize[],
};

/**
 *  One column (row) in a board: a name, the notes placed in it (ordered), and an
 *  optional tag that is auto-applied/removed as cards enter/leave the column.
 */
export type KanbanColumn = KanbanColumn_Serialize | KanbanColumn_Deserialize;

/**
 *  One column (row) in a board: a name, the notes placed in it (ordered), and an
 *  optional tag that is auto-applied/removed as cards enter/leave the column.
 */
export type KanbanColumn_Deserialize = {
	id: string,
	name: string,
	/**
	 *  The tag auto-assigned to notes dropped here (and removed when they leave).
	 *  `None` means this column has no tag automation.
	 */
	tag?: string | null,
	/**
	 *  Ordered note ids placed in this column. A note appears at most once per
	 *  board (adding it to a second column moves it).
	 */
	note_ids?: string[],
};

/**
 *  One column (row) in a board: a name, the notes placed in it (ordered), and an
 *  optional tag that is auto-applied/removed as cards enter/leave the column.
 */
export type KanbanColumn_Serialize = {
	id: string,
	name: string,
	/**
	 *  The tag auto-assigned to notes dropped here (and removed when they leave).
	 *  `None` means this column has no tag automation.
	 */
	tag?: string | null,
	/**
	 *  Ordered note ids placed in this column. A note appears at most once per
	 *  board (adding it to a second column moves it).
	 */
	note_ids: string[],
};

/**
 *  A misspelled span within checked text. `offset`/`length` are in **UTF-16 code
 *  units**, so they line up directly with JavaScript string indexing — the editor
 *  (step 5) decorates ProseMirror text nodes, which address text in JS string
 *  units, not Rust bytes or Unicode scalars.
 */
export type Misspelling = {
	offset: number,
	length: number,
	word: string,
	suggestions: string[],
};

/**  A full note document — one JSON file per note. */
export type Note = Note_Serialize | Note_Deserialize;

/**
 *  A specific note's content changed on disk, not caused by this app's own
 *  write. The frontend applies the clean/dirty/deleted reconciliation policy
 *  if it's the currently open note.
 */
export type NoteChangedExternally = {
	id: string,
};

/**
 *  A note→date link stored on the note (`NoteMeta::dates`). A bare date, plus an
 *  optional `event_id` when the link is to a specific event rather than just a day.
 */
export type NoteDate = NoteDate_Serialize | NoteDate_Deserialize;

/**
 *  A note→date link surfaced by a range query, carrying just enough of the note's
 *  summary (title/icon) to render and open it without a file read.
 */
export type NoteDateEntry = NoteDateEntry_Serialize | NoteDateEntry_Deserialize;

/**
 *  A note→date link surfaced by a range query, carrying just enough of the note's
 *  summary (title/icon) to render and open it without a file read.
 */
export type NoteDateEntry_Deserialize = {
	note_id: string,
	title: string,
	icon?: Icon | null,
	date: string,
	event_id?: string | null,
};

/**
 *  A note→date link surfaced by a range query, carrying just enough of the note's
 *  summary (title/icon) to render and open it without a file read.
 */
export type NoteDateEntry_Serialize = {
	note_id: string,
	title: string,
	icon?: Icon | null,
	date: string,
	event_id?: string | null,
};

/**
 *  A note→date link stored on the note (`NoteMeta::dates`). A bare date, plus an
 *  optional `event_id` when the link is to a specific event rather than just a day.
 */
export type NoteDate_Deserialize = {
	date: string,
	event_id?: string | null,
};

/**
 *  A note→date link stored on the note (`NoteMeta::dates`). A bare date, plus an
 *  optional `event_id` when the link is to a specific event rather than just a day.
 */
export type NoteDate_Serialize = {
	date: string,
	event_id?: string | null,
};

/**  Note-level metadata that is cheap to read and useful for listings. */
export type NoteMeta = NoteMeta_Serialize | NoteMeta_Deserialize;

/**  Note-level metadata that is cheap to read and useful for listings. */
export type NoteMeta_Deserialize = {
	pinned?: boolean,
	tags?: string[],
	/**
	 *  Optional top-of-page banner (cover). `#[serde(default)]` + skip-if-none, so
	 *  notes without a banner load and save exactly as before — no `SCHEMA_VERSION`
	 *  bump. Not mirrored into `NoteSummary`: the banner is only rendered in the
	 *  open editor, never in listings, so it never needs to be read without the
	 *  note body.
	 */
	banner?: Banner | null,
	/**
	 *  Note→date links (Phase 3 step 1). Optional and `#[serde(default)]`, so old
	 *  note files without it load unchanged — no `SCHEMA_VERSION` bump. Mirrored
	 *  into `NoteSummary` + the in-memory index (like `pinned`) so calendar range
	 *  queries never re-read note files.
	 */
	dates?: NoteDate_Deserialize[],
	/**
	 *  User-defined property values, keyed by the property's id (folder table
	 *  view). The **definitions** (name, type, select options) are folder-scoped
	 *  and owned by the frontend in `.vault/config/folder-views.json`; the core
	 *  stores each note's *values* opaquely (like `Block.props`/`content`) so it
	 *  never re-implements the property-type system. Mirrored into `NoteSummary`
	 *  (same pattern as `tags`/`dates`) so the table renders every row without
	 *  loading note bodies. `#[serde(default)]`, so old notes load unchanged — no
	 *  `SCHEMA_VERSION` bump.
	 */
	properties?: { [key in string]: any },
};

/**  Note-level metadata that is cheap to read and useful for listings. */
export type NoteMeta_Serialize = {
	pinned: boolean,
	tags: string[],
	/**
	 *  Optional top-of-page banner (cover). `#[serde(default)]` + skip-if-none, so
	 *  notes without a banner load and save exactly as before — no `SCHEMA_VERSION`
	 *  bump. Not mirrored into `NoteSummary`: the banner is only rendered in the
	 *  open editor, never in listings, so it never needs to be read without the
	 *  note body.
	 */
	banner?: Banner | null,
	/**
	 *  Note→date links (Phase 3 step 1). Optional and `#[serde(default)]`, so old
	 *  note files without it load unchanged — no `SCHEMA_VERSION` bump. Mirrored
	 *  into `NoteSummary` + the in-memory index (like `pinned`) so calendar range
	 *  queries never re-read note files.
	 */
	dates: NoteDate_Serialize[],
	/**
	 *  User-defined property values, keyed by the property's id (folder table
	 *  view). The **definitions** (name, type, select options) are folder-scoped
	 *  and owned by the frontend in `.vault/config/folder-views.json`; the core
	 *  stores each note's *values* opaquely (like `Block.props`/`content`) so it
	 *  never re-implements the property-type system. Mirrored into `NoteSummary`
	 *  (same pattern as `tags`/`dates`) so the table renders every row without
	 *  loading note bodies. `#[serde(default)]`, so old notes load unchanged — no
	 *  `SCHEMA_VERSION` bump.
	 */
	properties?: { [key in string]: any },
};

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary = NoteSummary_Serialize | NoteSummary_Deserialize;

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary_Deserialize = {
	id: string,
	title: string,
	/**  Path of the note file relative to the vault root (portable identity aid). */
	path: string,
	modified: string,
	/**
	 *  Note creation time, mirrored from the note file so the folder table view
	 *  can sort by "date created" without reading every note body.
	 */
	created: string,
	/**
	 *  On-disk size of the note file in bytes, captured at index/write time so
	 *  the folder table view can sort by size. Derived/cheap — a stale value
	 *  self-heals on the note's next write or an external-change reconcile.
	 *  `u32` (not `u64`): specta forbids exporting bigint types, and a JSON note
	 *  file never approaches 4 GB (attachments are separate files) — the helper
	 *  saturates rather than wraps just in case.
	 */
	size?: number,
	icon?: Icon | null,
	/**
	 *  Mirror of `NoteMeta::pinned`, carried in the summary so listings (the
	 *  Home dashboard's Pinned widget, Phase 2 step 6) can filter without
	 *  re-reading files.
	 */
	pinned?: boolean,
	/**
	 *  Mirror of `NoteMeta::dates` (Phase 3 step 1), carried in the summary +
	 *  in-memory index so calendar range queries are served without re-reading
	 *  note files — the same pattern as `pinned`.
	 */
	dates?: NoteDate_Deserialize[],
	/**
	 *  Mirror of `NoteMeta::tags` (Phase 3+ / Kanban), carried in the summary +
	 *  in-memory index so tag-driven listings (the Kanban board resolving its
	 *  cards, tag filters) never re-read note files — same pattern as `dates`.
	 */
	tags?: string[],
	/**
	 *  Mirror of `NoteMeta::properties` (folder table view), carried in the
	 *  summary + in-memory index so the table renders/sorts every row's custom
	 *  property values without loading note bodies — same pattern as `tags`.
	 */
	properties?: { [key in string]: any },
};

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary_Serialize = {
	id: string,
	title: string,
	/**  Path of the note file relative to the vault root (portable identity aid). */
	path: string,
	modified: string,
	/**
	 *  Note creation time, mirrored from the note file so the folder table view
	 *  can sort by "date created" without reading every note body.
	 */
	created: string,
	/**
	 *  On-disk size of the note file in bytes, captured at index/write time so
	 *  the folder table view can sort by size. Derived/cheap — a stale value
	 *  self-heals on the note's next write or an external-change reconcile.
	 *  `u32` (not `u64`): specta forbids exporting bigint types, and a JSON note
	 *  file never approaches 4 GB (attachments are separate files) — the helper
	 *  saturates rather than wraps just in case.
	 */
	size: number,
	icon?: Icon | null,
	/**
	 *  Mirror of `NoteMeta::pinned`, carried in the summary so listings (the
	 *  Home dashboard's Pinned widget, Phase 2 step 6) can filter without
	 *  re-reading files.
	 */
	pinned: boolean,
	/**
	 *  Mirror of `NoteMeta::dates` (Phase 3 step 1), carried in the summary +
	 *  in-memory index so calendar range queries are served without re-reading
	 *  note files — the same pattern as `pinned`.
	 */
	dates: NoteDate_Serialize[],
	/**
	 *  Mirror of `NoteMeta::tags` (Phase 3+ / Kanban), carried in the summary +
	 *  in-memory index so tag-driven listings (the Kanban board resolving its
	 *  cards, tag filters) never re-read note files — same pattern as `dates`.
	 */
	tags: string[],
	/**
	 *  Mirror of `NoteMeta::properties` (folder table view), carried in the
	 *  summary + in-memory index so the table renders/sorts every row's custom
	 *  property values without loading note bodies — same pattern as `tags`.
	 */
	properties?: { [key in string]: any },
};

/**  A full note document — one JSON file per note. */
export type Note_Deserialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta?: NoteMeta_Deserialize,
	blocks?: Block_Deserialize[],
};

/**  A full note document — one JSON file per note. */
export type Note_Serialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta: NoteMeta_Serialize,
	blocks: Block_Serialize[],
};

/**  One ranked search result. */
export type SearchHit = {
	id: string,
	title: string,
	snippet: string,
};

/**  The available (bundled) vs. currently-enabled spellcheck languages. */
export type SpellLanguages = {
	/**  Language codes with a bundled `<lang>.aff`+`<lang>.dic` resource. */
	available: string[],
	/**  Language codes currently enabled (app-setting; defaults to all available). */
	enabled: string[],
};

/**
 *  Lightweight listing entry for a reusable note template (see the `templates`
 *  section on `Vault`). Templates are `Note`-shaped documents kept OUTSIDE
 *  `notes/` (under the vault's `templates/` directory), so they never appear in
 *  the note tree, search, links, or graph — the same "not one of the vault's
 *  notes" treatment as the quick-note scratchpad. Only the cheap-to-show fields
 *  are carried across the boundary; the full block tree is loaded on demand via
 *  `read_template`.
 */
export type TemplateSummary = TemplateSummary_Serialize | TemplateSummary_Deserialize;

/**
 *  Lightweight listing entry for a reusable note template (see the `templates`
 *  section on `Vault`). Templates are `Note`-shaped documents kept OUTSIDE
 *  `notes/` (under the vault's `templates/` directory), so they never appear in
 *  the note tree, search, links, or graph — the same "not one of the vault's
 *  notes" treatment as the quick-note scratchpad. Only the cheap-to-show fields
 *  are carried across the boundary; the full block tree is loaded on demand via
 *  `read_template`.
 */
export type TemplateSummary_Deserialize = {
	id: string,
	title: string,
	icon?: Icon | null,
};

/**
 *  Lightweight listing entry for a reusable note template (see the `templates`
 *  section on `Vault`). Templates are `Note`-shaped documents kept OUTSIDE
 *  `notes/` (under the vault's `templates/` directory), so they never appear in
 *  the note tree, search, links, or graph — the same "not one of the vault's
 *  notes" treatment as the quick-note scratchpad. Only the cheap-to-show fields
 *  are carried across the boundary; the full block tree is loaded on demand via
 *  `read_template`.
 */
export type TemplateSummary_Serialize = {
	id: string,
	title: string,
	icon?: Icon | null,
};

/**
 *  The folder/note tree changed shape, or a note's title/icon changed on
 *  disk — the frontend should refresh the nav tree.
 */
export type TreeChanged = null;

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode = TreeNode_Serialize | TreeNode_Deserialize;

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode_Deserialize = { kind: "Folder"; data: FolderNode_Deserialize } | { kind: "Note"; data: NoteSummary_Deserialize };

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode_Serialize = { kind: "Folder"; data: FolderNode_Serialize } | { kind: "Note"; data: NoteSummary_Serialize };

/**  Summary of an open vault handed back across the IPC boundary. */
export type VaultInfo = {
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

