// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Suggested default vault location for the "don't make me think" path:
	 *  `{Documents}/Tundra` (CLAUDE.md §5.1).
	 */
	defaultVaultPath: () => typedError<string, CoreError>(__TAURI_INVOKE("default_vault_path")),
	/**  The last vault opened, if any — lets the app skip onboarding on relaunch. */
	lastVault: () => typedError<string | null, CoreError>(__TAURI_INVOKE("last_vault")),
	/**  Open (or create) the vault at `path`, remember it, and return its info. */
	openVault: (path: string) => typedError<VaultInfo, CoreError>(__TAURI_INVOKE("open_vault", { path })),
	/**  Info about the currently open vault, or `None` if onboarding is needed. */
	currentVault: () => typedError<{
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
} | null, CoreError>(__TAURI_INVOKE("current_vault")),
	listNotes: () => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("list_notes")),
	createNote: (title: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_note", { title })),
	/**
	 *  Create a note directly inside `folder` (relative to the notes root, `""`
	 *  for the root) — the "new note in the selected folder" nav action.
	 */
	createNoteIn: (title: string, folder: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_note_in", { title, folder })),
	readNote: (id: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("read_note", { id })),
	saveNote: (note: Note_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("save_note", { note })),
	deleteNote: (id: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_note", { id })),
	moveNote: (id: string, newFolder: string) => typedError<null, CoreError>(__TAURI_INVOKE("move_note", { id, newFolder })),
	/**  The folder/note tree for the open vault. */
	listTree: () => typedError<TreeNode_Serialize[], CoreError>(__TAURI_INVOKE("list_tree")),
	createFolder: (path: string) => typedError<null, CoreError>(__TAURI_INVOKE("create_folder", { path })),
	renameFolder: (path: string, newName: string) => typedError<null, CoreError>(__TAURI_INVOKE("rename_folder", { path, newName })),
	moveFolder: (path: string, newParent: string) => typedError<null, CoreError>(__TAURI_INVOKE("move_folder", { path, newParent })),
	deleteFolder: (path: string) => typedError<null, CoreError>(__TAURI_INVOKE("delete_folder", { path })),
	/**
	 *  Copy `src_path` (chosen via the native file dialog in `services`) into
	 *  `attachments/icons/`, returning its vault-relative path for `Icon::Custom`.
	 */
	importIcon: (srcPath: string) => typedError<string, CoreError>(__TAURI_INVOKE("import_icon", { srcPath })),
	/**
	 *  Import an attachment by content (Phase 2 step 1): the frontend reads a
	 *  browser `File`'s bytes and forwards them here; the core hashes them (blake3),
	 *  stores them content-addressed under `attachments/<kind>/`, and returns the
	 *  vault-relative path the editor stores in the embedding block. No attachment
	 *  bytes are ever written from the frontend.
	 */
	importAttachment: (kind: AttachmentKind, fileName: string, bytes: number[]) => typedError<string, CoreError>(__TAURI_INVOKE("import_attachment", { kind, fileName, bytes })),
	/**  Ranked full-text search hits (id, title, snippet) for `query`. */
	searchQuery: (query: string, limit: number) => typedError<SearchHit[], CoreError>(__TAURI_INVOKE("search_query", { query, limit })),
	/**
	 *  Rebuild the search index from scratch (a user-triggered recovery action —
	 *  the index is derived/rebuildable, never a source of truth).
	 */
	rebuildIndex: () => typedError<null, CoreError>(__TAURI_INVOKE("rebuild_index")),
	/**
	 *  Notes that link *to* `id` (incoming links), as current summaries — the
	 *  editor's backlinks panel (Phase 2 step 2).
	 */
	backlinks: (id: string) => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("backlinks", { id })),
	/**
	 *  The whole directed link graph (nodes = notes, edges = resolved links) for
	 *  the graph view (Phase 2 step 2/4). Broken links are excluded.
	 */
	graphData: () => typedError<GraphData, CoreError>(__TAURI_INVOKE("graph_data")),
	/**
	 *  Resolve note ids to their CURRENT summaries (title/icon) — for live link
	 *  labels; ids that no longer resolve are omitted (the caller uses the stored
	 *  label for those).
	 */
	resolveTitles: (ids: string[]) => typedError<NoteSummary_Serialize[], CoreError>(__TAURI_INVOKE("resolve_titles", { ids })),
	/**
	 *  Rebuild the link graph from the notes on disk (recovery action — the graph
	 *  cache is derived/rebuildable).
	 */
	rebuildGraph: () => typedError<null, CoreError>(__TAURI_INVOKE("rebuild_graph")),
	/**
	 *  Read a vault-scoped config file under `.vault/config/<name>` (Phase 2 step 4:
	 *  graph view settings; step 6: home dashboard layout). Returns the raw JSON
	 *  string, or `None` if it hasn't been written yet — the caller parses it. This
	 *  keeps vault UI state out of `localStorage` and in the vault where it can sync
	 *  (CLAUDE.md §4/§5.2).
	 */
	readVaultConfig: (name: string) => typedError<string | null, CoreError>(__TAURI_INVOKE("read_vault_config", { name })),
	/**
	 *  Write a vault-scoped config file under `.vault/config/<name>` atomically —
	 *  the FS counterpart of `read_vault_config`.
	 */
	writeVaultConfig: (name: string, contents: string) => typedError<null, CoreError>(__TAURI_INVOKE("write_vault_config", { name, contents })),
};

/** Events */
export const events = {
	noteChangedExternally: makeEvent<NoteChangedExternally>("note-changed-externally"),
	treeChanged: makeEvent<TreeChanged>("tree-changed"),
};

/* Types */
/**
 *  Which attachment library an import lands in (CLAUDE.md §5.2:
 *  `attachments/{images,videos,files}`). Crosses the IPC boundary, so it is
 *  serialized; the frontend maps a file's MIME type onto one of these.
 */
export type AttachmentKind = "image" | "video" | "file";

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block = Block_Serialize | Block_Deserialize;

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Deserialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Deserialize[],
};

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Serialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Serialize[],
};

export type CoreError = 
/**  No vault is currently open, or the path is not a usable vault. */
{ kind: "Vault"; message: string } | 
/**  A requested note could not be found by id. */
{ kind: "NotFound"; message: string } | 
/**  The stored schema version is newer than this build understands. */
{ kind: "SchemaTooNew"; message: {
	found: number,
	supported: number,
} } | 
/**  Underlying filesystem failure. */
{ kind: "Io"; message: string } | 
/**  JSON (de)serialization failure — a corrupt or malformed note file. */
{ kind: "Serde"; message: string } | 
/**  A block in the tree had an empty `id` (violates the CRDT-ready guarantee). */
{ kind: "EmptyBlockId" } | 
/**  The same block `id` appeared more than once in the tree. */
{ kind: "DuplicateBlockId"; message: string };

export type FolderNode = FolderNode_Serialize | FolderNode_Deserialize;

export type FolderNode_Deserialize = {
	name: string,
	/**
	 *  Forward-slash-separated path relative to the notes root, e.g.
	 *  `"Biology/Plants"` — the same shape every folder-op command takes.
	 */
	path: string,
	children: TreeNode_Deserialize[],
};

export type FolderNode_Serialize = {
	name: string,
	/**
	 *  Forward-slash-separated path relative to the notes root, e.g.
	 *  `"Biology/Plants"` — the same shape every folder-op command takes.
	 */
	path: string,
	children: TreeNode_Serialize[],
};

/**
 *  The whole link graph for the vault: every note as a node, resolved links as
 *  directed edges.
 */
export type GraphData = {
	nodes: GraphNode[],
	edges: GraphEdge[],
};

/**
 *  A directed graph edge — note `source` links to note `target`. Only emitted
 *  when both ends resolve to existing notes (broken links are not edges).
 */
export type GraphEdge = {
	source: string,
	target: string,
};

/**  A graph node — one note. */
export type GraphNode = {
	id: string,
	title: string,
};

/**  A per-note icon: a Twemoji codepoint or a custom vector/image in the vault. */
export type Icon = 
/**  Twemoji codepoint string, e.g. `"1f331"`. */
{ type: "emoji"; value: string } | 
/**  Path (relative to the vault) of a custom icon under `attachments/icons/`. */
{ type: "custom"; value: string };

/**  A full note document — one JSON file per note. */
export type Note = Note_Serialize | Note_Deserialize;

/**
 *  A specific note's content changed on disk, not caused by this app's own
 *  write. The frontend applies the clean/dirty/deleted reconciliation policy
 *  if it's the currently open note.
 */
export type NoteChangedExternally = {
	id: string,
};

/**  Note-level metadata that is cheap to read and useful for listings. */
export type NoteMeta = {
	pinned?: boolean,
	tags?: string[],
};

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary = NoteSummary_Serialize | NoteSummary_Deserialize;

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary_Deserialize = {
	id: string,
	title: string,
	/**  Path of the note file relative to the vault root (portable identity aid). */
	path: string,
	modified: string,
	icon?: Icon | null,
};

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary_Serialize = {
	id: string,
	title: string,
	/**  Path of the note file relative to the vault root (portable identity aid). */
	path: string,
	modified: string,
	icon?: Icon | null,
};

/**  A full note document — one JSON file per note. */
export type Note_Deserialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta?: NoteMeta,
	blocks?: Block_Deserialize[],
};

/**  A full note document — one JSON file per note. */
export type Note_Serialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta: NoteMeta,
	blocks: Block_Serialize[],
};

/**  One ranked search result. */
export type SearchHit = {
	id: string,
	title: string,
	snippet: string,
};

/**
 *  The folder/note tree changed shape, or a note's title/icon changed on
 *  disk — the frontend should refresh the nav tree.
 */
export type TreeChanged = null;

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode = TreeNode_Serialize | TreeNode_Deserialize;

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode_Deserialize = { kind: "Folder"; data: FolderNode_Deserialize } | { kind: "Note"; data: NoteSummary_Deserialize };

/**
 *  A folder/note tree node, as served by `list_tree` (built from the
 *  in-memory index — no disk reads beyond what `Vault::open` already did).
 */
export type TreeNode_Serialize = { kind: "Folder"; data: FolderNode_Serialize } | { kind: "Note"; data: NoteSummary_Serialize };

/**  Summary of an open vault handed back across the IPC boundary. */
export type VaultInfo = {
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

