// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Suggested default vault location for the "don't make me think" path:
	 *  `{Documents}/Tundra` (CLAUDE.md §5.1).
	 */
	defaultVaultPath: () => typedError<string, CoreError>(__TAURI_INVOKE("default_vault_path")),
	/**  The last vault opened, if any — lets the app skip onboarding on relaunch. */
	lastVault: () => typedError<string | null, CoreError>(__TAURI_INVOKE("last_vault")),
	/**  Open (or create) the vault at `path`, remember it, and return its info. */
	openVault: (path: string) => typedError<VaultInfo, CoreError>(__TAURI_INVOKE("open_vault", { path })),
	/**  Info about the currently open vault, or `None` if onboarding is needed. */
	currentVault: () => typedError<{
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
} | null, CoreError>(__TAURI_INVOKE("current_vault")),
	listNotes: () => typedError<NoteSummary[], CoreError>(__TAURI_INVOKE("list_notes")),
	createNote: (title: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("create_note", { title })),
	readNote: (id: string) => typedError<Note_Serialize, CoreError>(__TAURI_INVOKE("read_note", { id })),
	saveNote: (note: Note_Deserialize) => typedError<null, CoreError>(__TAURI_INVOKE("save_note", { note })),
};

/* Types */
/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block = Block_Serialize | Block_Deserialize;

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Deserialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Deserialize[],
};

/**
 *  A single typed block in the note tree.
 * 
 *  `props` and `content` are intentionally free-form JSON: BlockNote owns the
 *  editing model (CLAUDE.md §6.1 `document`), so the core stores the block tree
 *  faithfully without re-implementing every block type's schema.
 */
export type Block_Serialize = {
	id: string,
	type: string,
	props?: any | null,
	content?: any | null,
	children?: Block_Serialize[],
};

export type CoreError = 
/**  No vault is currently open, or the path is not a usable vault. */
{ kind: "Vault"; message: string } | 
/**  A requested note could not be found by id. */
{ kind: "NotFound"; message: string } | 
/**  The stored schema version is newer than this build understands. */
{ kind: "SchemaTooNew"; message: {
	found: number,
	supported: number,
} } | 
/**  Underlying filesystem failure. */
{ kind: "Io"; message: string } | 
/**  JSON (de)serialization failure — a corrupt or malformed note file. */
{ kind: "Serde"; message: string };

/**  A per-note icon: a Twemoji codepoint or a custom vector/image in the vault. */
export type Icon = 
/**  Twemoji codepoint string, e.g. `"1f331"`. */
{ type: "emoji"; value: string } | 
/**  Path (relative to the vault) of a custom icon under `attachments/icons/`. */
{ type: "custom"; value: string };

/**  A full note document — one JSON file per note. */
export type Note = Note_Serialize | Note_Deserialize;

/**  Note-level metadata that is cheap to read and useful for listings. */
export type NoteMeta = {
	pinned?: boolean,
	tags?: string[],
};

/**  Lightweight listing entry for the note tree — avoids loading full block trees. */
export type NoteSummary = {
	id: string,
	title: string,
	/**  Path of the note file relative to the vault root (portable identity aid). */
	path: string,
	modified: string,
};

/**  A full note document — one JSON file per note. */
export type Note_Deserialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta?: NoteMeta,
	blocks?: Block_Deserialize[],
};

/**  A full note document — one JSON file per note. */
export type Note_Serialize = {
	schemaVersion: number,
	id: string,
	title: string,
	icon?: Icon | null,
	created: string,
	modified: string,
	meta: NoteMeta,
	blocks: Block_Serialize[],
};

/**  Summary of an open vault handed back across the IPC boundary. */
export type VaultInfo = {
	/**  Display name (the vault folder's file name). */
	name: string,
	/**  Absolute path to the vault root. */
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

